### ISSUE TITLE
es6-tween?

### ISSUE THREAD

**Issue by dalisoft** [sergey-pimenov/awesome-web-animation#7]
Hi @sergey-pimenov 

Can you add es6-tween to list of js animation library?
It has good plugins and nice performance.

https://github.com/tweenjs/es6-tween

**Comment by sergey-pimenov** [comment]
@dalisoft Hi! [Done](https://github.com/sergey-pimenov/awesome-web-animation/commit/a750b81a4e6bc0e619dc91e49b40ad582c582255)

**Comment by dalisoft** [comment]
Thanks
